### ISSUE TITLE
Sort Posts [ Feed Page ] | Route:  /post

### ISSUE THREAD

**Issue by duracellB** [Find-Color/find-color-repo#5]
> users will have a dropdown to sort feed by various aspects

#### Acceptance Criteria
1. A dropdown "Sort" button is at the top of the feed page, and displays sort options
2. Sorting options include:
a. Most Recent
b. Oldest
c. Most Upvotes
d. Least Upvotes
3. Upon changing the Sort input, Posts will be sorted in appropriate order

**Comment by matsantos114** [comment]
The React component will be named Feed.jsx
